-- SELECT
--     concat('https://github.com/', v:repo.name, '/commit/', cast(v:payload.commit_id as string)) URL,
--     cast(v:payload.commit_id as string) AS commit_id,
--     count() AS comments,
--     count(distinct v:actor.login) AS authors
-- FROM github_events
-- WHERE (v:type = 'CommitCommentEvent') AND commit_id != ""
-- GROUP BY
--     v:repo.name,
--     commit_id 
-- HAVING authors >= 10
-- ORDER BY count() DESC, URL, authors
-- LIMIT 50
