name: Auto Comment Run Build All
on:
  pull_request_target:
    types:
      - opened
      - synchronize
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: "run buildall"
          pullRequestSynchronize: "run buildall"
